(deftheme jbeans
  "Created 2017-05-20.")

(custom-theme-set-variables
 'jbeans
 '(linum-format " %3i "))

(custom-theme-set-faces
 'jbeans
 '(alchemist-test--failed-face ((((class color) (min-colors 89)) (:foreground "#cf6a4c"))))
 '(alchemist-test--success-face ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground nil :background "#474e90"))))
 '(company-scrollbar-bg ((t (:background "#232323"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#888888"))))
 '(company-tooltip ((t (:background "#232323" :foreground "#cccccc" :weight bold))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#8197bf"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#cccccc" :underline nil :weight bold))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#474e90"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#cf6a4c"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#888888"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#cf6a4c"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(elixir-atom-face ((((class color) (min-colors 89)) (:foreground "#8fbfdc"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#8fbfdc"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#888888"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#447799"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8197bf"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#ffb964"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cf6a4c"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dd0093"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#fad07a" :bold t))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#cf6a4c" :bold t))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#151515"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:background "#335533" :foreground "#151515"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#8197bf"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#151515"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#b2e2fe"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "#dd0093" :background "#151515"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#333344"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:foreground "#fad07a" :background "#151515"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#b2e2fe"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#333344"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#222222"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#dd0093"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#dd0093"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#8197bf"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#dd0093" :background nil))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#444444" :background "#222222"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:inherit mode-line :background "#151515"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:inherit mode-line :background "#333344"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:inherit mode-line :background "#151515"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:inherit mode-line :background "#222222"))))
 '(match ((((class color) (min-colors 89)) (:background "#dd0093"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#fad07a"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#333344"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#7f7f7f" :background "#151515"))))
 '(org-checkbox ((((class color) (min-colors 89)) (:foreground "#99ad6a"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#8197bf"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#ffdddd"))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#448844"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#ffb964" :weight bold))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#99ad6a" :weight bold))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#cb8165"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#8fbfdc"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#8197bf"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#ffb964"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#cf6a4c"))))
 '(region ((((class color) (min-colors 89)) (:background "#333344"))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#222222"))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:background "#444444"))))
 '(spaceline-evil-normal ((((class color) (min-colors 89)) (:foreground "#151515" :background "#b78521"))))
 '(spaceline-evil-motion ((((class color) (min-colors 89)) (:foreground "#151515" :background "#a40073"))))
 '(spaceline-evil-insert ((((class color) (min-colors 89)) (:foreground "#151515" :background "#448844"))))
 '(spaceline-evil-visual ((((class color) (min-colors 89)) (:foreground "#151515" :background "#444444"))))
 '(spaceline-evil-replace ((((class color) (min-colors 89)) (:foreground "#151515" :background "#cf6a4c"))))
 '(spaceline-evil-emacs ((((class color) (min-colors 89)) (:foreground "#151515" :background "#2dfffe"))))
 '(spacemacs-normal-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#b78521"))))
 '(spacemacs-motion-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#a40073"))))
 '(spacemacs-insert-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#448844"))))
 '(spacemacs-visual-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#444444"))))
 '(spacemacs-lisp-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#cd00cd"))))
 '(spacemacs-replace-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#cf6a4c"))))
 '(spacemacs-iedit-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#fc0d1b"))))
 '(spacemacs-iedit-insert-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#fc0d1b"))))
 '(spacemacs-evilified-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#556a32"))))
 '(spacemacs-emacs-face ((((class color) (min-colors 89)) (:foreground "#151515" :background "#2dfffe"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dd0093"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#333344"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#151515")))))

(provide-theme 'jbeans)
